### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by argupta23** [vijhhh2/Nebular-Formly#1]
Hello Vijay,

I am interested in using your library with Nebular and Ngx-formly bundled together.
Can I please request your guidance on how I could go about integrating it?

I would also suggest you reach out to the developer of ngx-formly and share the work you have done as he has Nebular support on the roadmap.

Looking forward to hear back from you.

Thanks

**Comment by vijhhh2** [comment]
Hi, @argupta23 This package is still in preview. We are using this in our projects and fixing some bugs. Soon we will update the documentation.
